import streamlit as st
import pandas as pd
import requests
import os
from datetime import datetime

# --- CONFIGURATION ---
CME_URL = "https://www.cmegroup.com/delivery_reports/Silver_stocks.xls"
LOCAL_FILE_PATH = "silver_stocks_data.xls"

# --- HELPER FUNCTIONS ---

def download_cme_report():
    """Downloads the latest Silver Stocks report from CME and saves it locally."""
        try:
                response = requests.get(CME_URL, timeout=10)
                        response.raise_for_status()
                                
                                        # Save the file to the project folder
                                                with open(LOCAL_FILE_PATH, 'wb') as f:
                                                            f.write(response.content)
                                                                        
                                                                                return True, "Download successful."
                                                                                    except Exception as e:
                                                                                            return False, f"Error downloading file: {e}"

                                                                                            def load_and_clean_data():
                                                                                                """Reads the local Excel file and extracts the relevant totals."""
                                                                                                    if not os.path.exists(LOCAL_FILE_PATH):
                                                                                                            return None, "File not found. Please download first."

                                                                                                                try:
                                                                                                                        # CME files have headers, so we read flexibly. 
                                                                                                                                # Usually data starts after row 5, but we search for the 'TOTAL' row.
                                                                                                                                        df = pd.read_excel(LOCAL_FILE_PATH)
                                                                                                                                                
                                                                                                                                                        # Clean up: Find the row that contains "TOTAL" in the first column
                                                                                                                                                                # This filters out the header logos and disclaimers
                                                                                                                                                                        total_row_index = df[df.iloc[:, 0].astype(str).str.contains("TOTAL", case=False, na=False)].index
                                                                                                                                                                                
                                                                                                                                                                                        if len(total_row_index) > 0:
                                                                                                                                                                                                    # Get the row with totals. 
                                                                                                                                                                                                                # Note: CME column layout changes slightly, but usually:
                                                                                                                                                                                                                            # Col 0: Name, ... Col X: Eligible, Col Y: Registered, Col Z: Total
                                                                                                                                                                                                                                        # We will grab the last row of the dataset which usually contains the Grand Totals
                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                # Re-reading with header=4 is a common trick for CME, 
                                                                                                                                                                                                                                                                            # but let's just grab the last valid row for the "Grand Total"
                                                                                                                                                                                                                                                                                        df_cleaned = pd.read_excel(LOCAL_FILE_PATH, header=4)
                                                                                                                                                                                                                                                                                                    df_cleaned = df_cleaned.dropna(how='all')
                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                            # Find the Grand Total row
                                                                                                                                                                                                                                                                                                                                        grand_total = df_cleaned[df_cleaned.iloc[:, 0].astype(str).str.contains("TOTAL", na=False)]
                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                return grand_total, df_cleaned
                                                                                                                                                                                                                                                                                                                                                                        else:
                                                                                                                                                                                                                                                                                                                                                                                    return None, "Could not parse Excel structure."
                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                    except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                            return None, f"Error parsing Excel: {e}"

                                                                                                                                                                                                                                                                                                                                                                                                            # --- UI LAYOUT ---

                                                                                                                                                                                                                                                                                                                                                                                                            st.set_page_config(page_title="Silver Squeeze Tracker", layout="wide")

                                                                                                                                                                                                                                                                                                                                                                                                            st.title("🥈 Real-Time Silver Stock Tracker")
                                                                                                                                                                                                                                                                                                                                                                                                            st.markdown("Monitor COMEX inventory levels to detect potential short squeeze signals.")

                                                                                                                                                                                                                                                                                                                                                                                                            # 1. SIDEBAR: CONTROLS
                                                                                                                                                                                                                                                                                                                                                                                                            with st.sidebar:
                                                                                                                                                                                                                                                                                                                                                                                                                st.header("Data Controls")
                                                                                                                                                                                                                                                                                                                                                                                                                    if st.button("Download Latest CME Data"):
                                                                                                                                                                                                                                                                                                                                                                                                                            with st.spinner("Fetching data from CME Group..."):
                                                                                                                                                                                                                                                                                                                                                                                                                                        success, msg = download_cme_report()
                                                                                                                                                                                                                                                                                                                                                                                                                                                    if success:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    st.success(f"{msg} Saved to {LOCAL_FILE_PATH}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Reload the page to reflect changes
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    st.rerun()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                st.error(msg)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        st.write(f"**Last Checked:** {datetime.now().strftime('%Y-%m-%d %H:%M')}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            st.info("Source: CME Group Official Delivery Reports")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # 2. MAIN LOGIC & DISPLAY
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            totals, full_data = load_and_clean_data()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if totals is not None:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Extracting Key Metrics (Assuming standard CME column order: Registered is usually Col 1, Eligible Col 2, but we use names if possible)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # We try to map columns by name, if not we fall back to index
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Normalize column names to uppercase for easier search
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            full_data.columns = [str(c).upper().strip() for c in full_data.columns]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Locate columns
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    reg_col = [c for c in full_data.columns if "REGISTERED" in c][0]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            elig_col = [c for c in full_data.columns if "ELIGIBLE" in c][0]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            registered_val = totals[reg_col].values[0]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    eligible_val = totals[elig_col].values[0]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # --- TOP METRICS ROW ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            col1, col2, col3 = st.columns(3)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            with col1:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        st.metric(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            label="📦 Registered (Available for Delivery)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            value=f"{registered_val:,.0f} oz",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            delta_color="inverse",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            help="REGISTERED = Metal that has a warrant attached and is ready to be delivered to settle a futures contract. **Impact:** If this number drops close to zero, short sellers cannot deliver physical silver, leading to a massive price spike (Squeeze)."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                with col2:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            st.metric(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                label="🔒 Eligible (Not Available)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                value=f"{eligible_val:,.0f} oz",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                help="ELIGIBLE = Metal sitting in the vault that meets purity standards but is privately owned and NOT for sale/delivery. **Impact:** High eligible stocks do not stop a squeeze unless the owners decide to sell and convert it to 'Registered'."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                with col3:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Custom Squeeze Ratio
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ratio = (eligible_val / registered_val) if registered_val > 0 else 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    st.metric(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        label="Squeeze Pressure (Eligible/Reg Ratio)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        value=f"{ratio:.2f}x",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        help="This ratio shows how much silver is 'locked up' vs available. A higher number means very little silver is actually available for market delivery."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            st.divider()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # --- DATA VIEWER ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            st.subheader("📋 Warehouse Data Breakdown")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Highlight the columns for the user
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    st.dataframe(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    full_data.style.applymap(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        lambda x: 'background-color: #d4edda; color: black', subset=[reg_col]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ).format("{:,.0f}", subset=[reg_col, elig_col]),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                use_container_width=True
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                st.error(f"Error mapping columns. CME may have changed headers. Details: {e}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        st.write("Raw Data for debugging:")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                st.write(full_data)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    st.warning("No data found. Click 'Download Latest CME Data' in the sidebar.")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # --- EDUCATIONAL TOOLTIPS (INFO SECTION) ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    with st.expander("ℹ️ How to read this data for trading (Click to Open)"):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        st.markdown("""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ### 📉 The Short Squeeze Signal
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Prices are affected by **Supply (Registered)** vs **Demand (Open Interest)**.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        * **If Registered Stocks Drop:** This is bullish. It means physical silver is leaving the vaults.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            * **If 'Eligible' is High but 'Registered' is Low:** This is the *danger zone* for shorts. It means there is silver in the vault, but the owners **refuse to sell it** at current prices.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    **Look for:** A rapid decrease in the Green highlighted column (Registered) combined with a rising silver price.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        """)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )